### ISSUE TITLE
More a question than Issue

### ISSUE THREAD

**Issue by NSiggel-CPX-PowerWatts** [tusdotnet/tusdotnet#103]
First off, nice work on the dotnet implementation.
Been doing some testing and works very nicely for files in the 1-4 Gb range.

Now this seems like a simple question, but how can I get rid of, clean up the files once I've done some processing on the actual data stream ?

I need to remove the file artifacts from the tusDiskStore once I've completed by Processing.

I tried doing things like
((ITusTerminationStore)ctx.Store).DeleteFileAsync(ctx.FileId, ctx.CancellationToken)
but getting exceptions 
Exception thrown: 'System.AggregateException' in mscorlib.dll

I realize the ITusTerminationStore purpose is different, but I just need a way to clean out all the tus artifact files 

3b52992f75d6423d9e65082870298470
3b52992f75d6423d9e65082870298470.chunkcomplete
3b52992f75d6423d9e65082870298470.chunkstart
3b52992f75d6423d9e65082870298470.expiration
3b52992f75d6423d9e65082870298470.metadata
3b52992f75d6423d9e65082870298470.uploadlength

once I've saved my raw stream to another location.

Suggestion greatly appreciated.

**Comment by smatsson** [comment]
Hi,

Thanks for the kind words! 

ITusTerminationStore is the way to go here. `System.AggregateException` is a combined exception so you would have to look at the `InnerExceptions` property of the exception to find out the issue. Most likely it's caused by the file stream being opened by some other part of the system.

**Comment by aspian-io** [comment]
Hi,

Thanks for this nice server-side implementation of Tus for .NET.

I am using this package with .net core 3.1 and my react app and uppy and it works fine. Just I have a couple of questions to ask you... 

1- I want to know, is there any way to access Tus endpoint (UrlPath) after **authorization**? because, now, I don't see any server side solutions to use authentication and authorization restrictions for Tus endpoint and I am using JWT with my react app so it could use authorization policies .... 

2- Another question is that, I am using **"FluentFTP"** to connect to a **FTP server with credentials** so how can I use that with Tus if I want to upload files through Tus directly to FTP server?

Thanks.
