### ISSUE TITLE
termination of files

### ISSUE THREAD

**Issue by KhaledSMQ** [tusdotnet/tusdotnet#106]
I am not sure the usage of delete api, I am trying to delete files but getting 404 and when I debug the code I found that validator   [FileHasNotExpired](https://github.com/tusdotnet/tusdotnet/blob/4f48a35cc162f487fba9aa2816621ec5149bed87/Source/tusdotnet/Validation/Requirements/FileHasNotExpired.cs#L25)  returning not found if the file did not pass expiration condition even if the file existing but in the [documentation](https://tus.io/protocols/resumable-upload.html#termination) of the protocol is says that I can delete completed and uncompleted files to free resources 
 >"This extension defines a way for the Client to terminate completed and unfinished uploads allowing the Server to free up used resources."

 Is this a bug or it's by design to prevent delete the files?

**Comment by smatsson** [comment]
Hi,

It's by design to not have to run a scheduler inside tusdotnet. When files are created the expiration timestamp is saved with the file and after that time the file can no longer be accessed, just as if it was deleted.

https://github.com/tusdotnet/tusdotnet/wiki/Removing-expired-incomplete-files

**Comment by KhaledSMQ** [comment]
thank you @smatsson for explain
