### ISSUE TITLE
Best practice - cached image uploads?

### ISSUE THREAD

**Issue by dylinmaust** [tusdotnet/tusdotnet#110]
I'm experiencing an issue using Uppy + Tus in a React application where successive uploads of images with different transformations (crop, rotate, zoom, etc.) return the first image.

To reproduce:
- Upload an image as normal
- Upload same image, but apply a crop or some other sort of transformation

Expected results:
- First image uploaded successfully with normal crop
- Second image uploaded successfully with crop applied

Actual results:
- First image uploaded successfully with normal crop
- Second image uploaded successfully, but is exactly the same as the first image

I've confirmed that using an image that has not been uploaded to the Tus server has the correct crop applied, which leads me to believe that Tus is deferring to the previously uploaded file.

Now, obviously resumable uploads is one of the selling points for using the Tus protocol. So I'm not sure what the best practice is here? Should I delete the existing file (if it exists) in `OnBeforeCreateAsync` or is there a better practice? If I understand correctly, the "delete before create approach" would essentially negate resumable uploads.

For our app, I can see this use case happening pretty frequently.

Thanks!

**Comment by smatsson** [comment]
Hi,

This sounds to me like the client does not create a new upload resource when the file is changed (e.g. crop applied). The client is responsible for keeping track of what upload resource (i.e. URL to uplod the file to) is associated with which file and it might not understand work properly when applying the transformation. The `OnBeforeCreate` event is only fired when the file is created so it won't fire for the cropped file if my theory is correct. In general I would not delete the files like that as, since you pointed out, that would break the whole resumability.

You could verify if my theory is correct by checking the network tab in your browser's dev tools. The requests would be something like this:
```
<user selects first file and uploads it>

Req: POST /files
Res: 201 Created with Location header /files/<guid>

Req: PATCH /files/<guid>
Res: 204 No Content

<user does cropping and re-uploads the file>

Req: HEAD /files/<guid>
Res: 204 No Content
```

**Comment by dylinmaust** [comment]
You're absolutely right. My mistake, I am new to this protocol so didn't understand if it was the client or server's responsibility for something like this. After doing more research, I've found that Uppy's Tus plugin configuration supports removing the file from cache on successful upload by setting the `removeFingerprintOnSuccess` property:

```
uppy.use(Tus, {
  endpoint,
  removeFingerprintOnSuccess: true,
});
```

For future readers, see below link for more information:
https://github.com/transloadit/uppy/issues/1171

**Comment by smatsson** [comment]
Glad it was solved! :)
