### ISSUE TITLE
How to remove the file when the file is uploaded completely

### ISSUE THREAD

**Issue by hashmat-ali** [tusdotnet/tusdotnet#113]
Is it possible to delete uploaded ITusFile (file) in the "OnFileCompleteAsync" event. 

Once the file is uploaded, I need to move it another location and remove it from tus disk store location. Please let me if it is duplicated issue and share any link which will point me in right direction to remove the file once the file upload is complete.

**Comment by smatsson** [comment]
Hi,

Given that the store being used supports termination (`TusDiskStore` does) you can just convert the `ITusStore` provided in the callback context to either the actual type of the store (e.g. `TusDiskStore`) or `ITusTerminationStore`:

```
OnFileCompleteAsync = async ctx =>
{
    ITusFile file = ctx.GetFileAsync();
    await MoveFile(file);

    var terminationStore = (ITusTerminationStore)ctx.Store;
    await terminationStore.DeleteFileAsync(file.Id, ctx.CancellationToken);
}
```

**Comment by hashmat-ali** [comment]
@smatsson 
I tried the above and got below error:
The process cannot access the file 'C:\tusfiles\{fileId}' because it is being used by another process. It seems the file is locked by w3wp. Is it possible to remove the lock?

**Comment by smatsson** [comment]
This is most likely because you forgot to close the file stream after moving the file.

**Comment by cdroulers** [comment]
I had the same question and this helped me! I couldn't find anything in the wiki explaining this!

This issue could be used to track a documentation update?

**Comment by smatsson** [comment]
@cdroulers Absolutley. The design idea with multiple interfaces turned out great internally in tusdotnet but makes it a bit difficult to work with from outside the lib. There have been talk about changing `DefaultTusConfiguration` to take a generic argument that is the store, which would then give each event the actual store and not the abstraction but no ETA is set.

If you want to contribute an update to the wiki, please feel free to submit a PR in this repo: https://github.com/tusdotnet/tusdotnet.wikisource

**Comment by smatsson** [comment]
Closing this as the wiki has been updated: https://github.com/tusdotnet/tusdotnet/wiki/Deleting-processed-files-when-upload-is-complete
