### ISSUE TITLE
Use tus as a service with own controller and endpoint

### ISSUE THREAD

**Issue by SimonNeP** [tusdotnet/tusdotnet#117]
Hello!

I'm trying to implement a service, which retrieves information about the uploader when an upload is started.
For example this service should check who is currently the one uploading a file and retrieves information from a database. Then I would like to call my tus implementation with the fileId from the db. I do not know if this is possible to be fair.

If my understanding is correct, you would just implement the different interfaces and declare an URL-endpoint like "/file". But with this, I wouldn't be able to know exactly who uploaded the file or if not another person uploads the same file.

Ideally I would like to implement my own controller, in which I can implement my logic (like in #116 suggested).

**Comment by smatsson** [comment]
Hi! 

If I understand you correct you wish to do two things:
* Separate files from different users so that they cannot access each others files
* Have a fileId generated from your database instead of the default GUID implementation

Is this correct? This is absolutely doable with the current implementation of tusdotnet.

The configuration factory called for each request supports returning different configurations for different users which gives you the ability to separate user storage. Example:

```csharp
app.UseTus(async httpContext => 
{
    if(!httpContext.User.Identity.IsAuthenticated)
        return null; // Disables tusdotnet for this request.

    string userStorageLocation = await GetUserStorageLocationFromDatabase(httpContext.User);

    return new DefaultTusConfiguration
    {
        Store = new TusDiskStore(userStorageLocation),
        UrlPath = "/files",
        Events = new Events
        {
            OnFileCompleteAsync = async eventContext =>
            {
                ITusFile file = await eventContext.GetFileAsync();
                await DoSomeProcessing(file);
            }
        }
    } 
});
```

For custom ids, check out this wiki page: https://github.com/tusdotnet/tusdotnet/wiki/Custom-File-Id-Provider

**Comment by SimonNeP** [comment]
Thanks for the quick answer, this does help!
