### ISSUE TITLE
How to implement file encryption?

### ISSUE THREAD

**Issue by msalai** [tusdotnet/tusdotnet#130]
I would like to encrypt files after (or during) file upload and I was wondering where and how to do it? I know how to implement encryption of bytes/files in general, just don't know how to intercept it before it is written to disk.

**Comment by smatsson** [comment]
Hi,

Without changing the source of tusdotnet I think you have three different options depending on your use case:

1. Use full disk encryption with e.g. Bitlocker. This would encrypt all files, all metadata, all logs etc and would also encrypt memory dumped to disk (e.g. Windows swap files).
2. Encrypt the file on the client with the server's public key before sending it. This would be a good choice if some other backend system is used for processing as the server running tusdotnet would not be able to decrypt the data.
3. Change the incoming request stream so that everything read from it is automatically encrypted before writing to disk. This might cause issues with offsets etc if the encrypted file size differs from the unencrypted one. Basically doing something like this:
```csharp
app.Use((ctx, next) =>
{
    ctx.Request.Body = new EncryptedStream(ctx.Request.Body);
    return next.Invoke();
});

app.UseTus(...);
```

If you want to build your own version of tusdotnet you can modify [this line](https://github.com/tusdotnet/tusdotnet/blob/master/Source/tusdotnet/Stores/TusDiskStore.cs#L107) to use a CryptoStream or similar.

**Comment by msalai** [comment]
Thank you very much
