### ISSUE TITLE
Remaining files after download completes

### ISSUE THREAD

**Issue by mkgn** [tusdotnet/tusdotnet#136]
Everything works perfect. So after upload completes and events are handled, the upload folder still contains below files.

![image](https://user-images.githubusercontent.com/8392595/118787834-d3142600-b8b0-11eb-9b69-4ca32177345d.png)

I am under the impression that upon a successful upload, it'll remove all intermediate files and keep the actual file or is it something I have to do in my code using the FileComplete event?

**Comment by tukao89** [comment]
You should implement ExpiredFilesCleanupService

**Comment by smatsson** [comment]
Hi! 

>Everything works perfect. So after upload completes and events are handled, the upload folder still contains below files.

Glad to hear that everything works as expected! tusdotnet will never remove any files simply because it does not know when you as a dev are finished with them. There are some exceptions to this but all of these exceptions require that the dev does something (setting a property, calling a method etc). The files listed are not temporary but are used for different things by tusdotnet. Simplest way to delete the file is to use the following approach: https://github.com/tusdotnet/tusdotnet/wiki/Deleting-processed-files-when-upload-is-complete

>You should implement ExpiredFilesCleanupService, something like bellow code

That wouldn't really help in this case as `ITusExpirationStore.RemoveExpiredFilesAsync` only deletes non-complete files that have expired. See https://github.com/tusdotnet/tusdotnet/wiki/Custom-data-store#itusexpirationstore

**Comment by mkgn** [comment]
Got it! Good advice I need both of the suggested things implemented. Thank you! I am closing the issue.
