### ISSUE TITLE
Issue getting user identity in OnAuthorizedAsync's eventContext

### ISSUE THREAD

**Issue by cdmoss** [tusdotnet/tusdotnet#140]
Hi. In my razor pages application that uses built in Identity authentication, I'm finding that I'm unable to check the identity of the current user in the eventContext for OnAuthorizedAsync. Here is the relevant  configuration 
```
OnAuthorizeAsync = async eventContext => {
                        var test = eventContext.HttpContext.User.Identity;

                        if (!eventContext.HttpContext.User.Identity.IsAuthenticated)
                        {
                            eventContext.FailRequest(System.Net.HttpStatusCode.Unauthorized);
                            return;
                        }
                        if (!eventContext.HttpContext.User.IsInRole("Developer"))
                        {
                            eventContext.FailRequest(System.Net.HttpStatusCode.Forbidden, "Only developers can upload.");
                            return;
                        }
                    }
```
The HttpContext seems to contain the identity of the logged in user in other xhr requests, as long as that HttpContext is accessed through the PageModel. I've inspected and compared such non-tus xhr requests to the tus xhr requests, and as far as I can tell they look exactly the same where it is relevant: same cookies, headers, both contain the request verification token. So I'm struggling to understand why HttpContext in the useTus configuration doesn't contain user Identity. Thanks in advance for clearing this up for me.

**Comment by smatsson** [comment]
Hi,

Without seeing the rest of your authentication setup I think this is similar to this issue here: https://github.com/tusdotnet/tusdotnet/issues/137#issuecomment-862703575

Have you configured a default authentication schema? If not, you should be able to challenge the request (and thus get the User identity) using [AuthenticationHttpContextExtensions.ChallengeAsync ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.authenticationhttpcontextextensions.challengeasync?view=aspnetcore-5.0).

Please let me know if any of this solved the issue. In a future version tusdotnet will integrate with endpoint routing making all of this easier.

**Comment by cdmoss** [comment]
ChallengeAsync didn't seem to work for me, though I could have been misusing it somehow.
I ended up using AuthenticationHttpContextExtensions.AuthenticateAsync, which returns an AuthenticationResult that includes the authenticated user claims. Thanks for pointing me in the right direction, and looking forward to the new improvements. The tus protocol is really exciting!

**Comment by smatsson** [comment]
Oops I linked you the wrong method. Sorry about that! Glad you solved it :) I'l update the docs to make this clearer.
