### ISSUE TITLE
Massive dependencies list to install in .NET Framework project

### ISSUE THREAD

**Issue by jarrodkoch** [tusdotnet/tusdotnet#168]
Hello,

I was attempting to install the tusdotnet library into an existing .NET Framework application (using NuGet).  However, I was presented with what seems like an immense list of dependencies which need to be included.

![image](https://user-images.githubusercontent.com/20542287/153472041-fe651fc8-d2a3-48e3-8435-c52d2dc1fa0e.png)

Am I doing something wrong?  There is no way I will be able to get approval to add the library if there is such a large number of dependencies which need to be included.  Is it not possible to use the library without all of these .NET Core dependencies?

**Comment by smatsson** [comment]
Hi,

You are not doing anything wrong afaik. In .NET Core they changed how assemblies are included so that all apps now references each assembly needed instead of everything being bundled with the framework. Since .NET Framework is basically dead I will not make any efforts into releasing a package without support for .NET Core. 

The way I see it you have three options:
1. Install the dependencies. All of them are official dependencies from Microsoft that would probably already be installed on your server anyway.
2. Come join us in the future and use .NET6, or at least setup a microservice running on .NET6 which will not require these dependencies.
3. Grab the source, throw out any code you don't want and maintain it yourself.

**Comment by jarrodkoch** [comment]
Totally understand that you aren't interested in creating/supporting a version of this that does not support .NET Core.

Thanks for the feedback.
