### ISSUE TITLE
upload rar file, the file type is empty

### ISSUE THREAD

**Issue by junshangshui** [tusdotnet/tusdotnet#173]
![000000000000000000](https://user-images.githubusercontent.com/40519621/167298860-ce86b0a1-acb1-463d-b46d-d006ed63a6cf.png)
i use chrome version:101

**Comment by smatsson** [comment]
Hard to tell without seeing any code. Where is the screenshot from?

**Comment by junshangshui** [comment]
> 
chrome DevTool 

function startUpload (){
var file = input.files[0]
...................
}

**Comment by junshangshui** [comment]
> Hard to tell without seeing any code. Where is the screenshot from?

chrome DevTool

function startUpload (){
var file = input.files[0]
...................
}

**Comment by smatsson** [comment]
What am I supposed to do with that code sample? It's incomplete and doesn't show what your code does.

**Comment by junshangshui** [comment]
> What am I supposed to do with that code sample? It's incomplete and doesn't show what your code does.

![8888888888888888](https://user-images.githubusercontent.com/40519621/167783517-b909e24b-fb1f-45aa-bdf2-dbf57a5ab339.png)
![9999999999999999999999999999999999](https://user-images.githubusercontent.com/40519621/167783516-df9ab17f-4177-4005-8ad7-3edcfbf43e2f.png)

**Comment by smatsson** [comment]
It's completely impossible to follow what you are trying to convey. Is the question why your browser doesn't provide you with a type for the file? "file" here is a native component of your browser. Educated guess is that the machine running the browser does not have any app installed to handle rar files and thus it does not know what type it is. The same happens if you have some other odd file extension, e.g.:
![image](https://user-images.githubusercontent.com/4600361/167832705-de6e81af-a687-45c4-8cb5-c4d01c05159b.png)

Your options are basically to install the needed software on the client or not depend on the type on the backend, either through checking the file name or examining the file signature.

**Comment by junshangshui** [comment]
> It's completely impossible to follow what you are trying to convey. Is the question why your browser doesn't provide you with a type for the file? "file" here is a native component of your browser. Educated guess is that the machine running the browser does not have any app installed to handle rar files and thus it does not know what type it is. The same happens if you have some other odd file extension, e.g.: ![image](https://user-images.githubusercontent.com/4600361/167832705-de6e81af-a687-45c4-8cb5-c4d01c05159b.png)
> 
> Your options are basically to install the needed software on the client or not depend on the type on the backend, either through checking the file name or examining the file signature.

thank you.
