### ISSUE TITLE
Exceptions thrown during OnFileCompleteAsync get swallowed when using create during creation

### ISSUE THREAD

**Issue by hahn-kev** [tusdotnet/tusdotnet#211]
I'm throwing an exception in the OnFileComplete event but it's not making it back to the client. Taking a look at the code [here](https://github.com/tusdotnet/tusdotnet/blob/4ab1116e0f84301a010dbddcc35fbfbdf701103b/Source/tusdotnet/Runners/TusV1EventRunner.cs#L94) it looks like it's getting suppressed intentionally.

It seems that if I set `uploadDataDuringCreation` to false (in the js client) then the error gets thrown properly after some retries.

**Comment by smatsson** [comment]
Hi,

The reason the entire exception is suppressed is because of how the `creation-with-upload` extension works:

1. The client can include a body in the initial request to save itself a round trip. 
2. The initial request returns the upload resource URL which can be used to continue the upload if anything goes wrong. 
 
This means that if the client includes data and something goes wrong (exception, loss of connection etc) there is no way for the client to resume the upload since it never received the resource URL. The client would need to restart the entire upload, even if 99% of the data was transferred correctly. Because of this tusdotnet does suppress exceptions that happen during writing for this extension so that the client can get the URL and continue the upload.

On the other hand, when the upload is already completed as in your case, there is no way for the client to continue the upload anyway.

The solution is probably to move the `await handler.NotifyAfterAction();` line outside the `try` block or that `swallowExceptionsDuringInvoke` should be changed to false after the call to `handler.Invoke()`. 

The quick fix for now is to disable `uploadDataDuringCreation` in the client. It doesn't add much latency (an extra POST request) but gives you the ability to actually resume the upload if the connection breaks down. Either that, or find a suitable chunk size and send that in the first request.
