### ISSUE TITLE
Custom data store enquery

### ISSUE THREAD

**Issue by tzupetic** [tusdotnet/tusdotnet#212]
Hello,
In my .net core web app, I need to upload videos to cloudflare using tus. I have implemented my custom class which is using interface ITusPipelineStore, but I am getting an error: "tus: unexpected response while creating upload, originated from request (method: POST, url: http://localhost:5000/files, response code: 404, response text: , request id: n/a)"

Are there some guidelines or is there some example of how should this custom store class be configured when using cloud services?

**Comment by smatsson** [comment]
Hi,

From the error message, and without seeing your code, I would guess that you did not implement the `ITusCreationStore` interface. This interface lets the tus client create a new upload resource to upload data to.

The documentation can be found here: https://github.com/tusdotnet/tusdotnet/wiki/Custom-data-store

>The most common interfaces to implement are [ITusStore](https://github.com/tusdotnet/tusdotnet/wiki/Custom-data-store#itusstore), [ITusCreationStore](https://github.com/tusdotnet/tusdotnet/wiki/Custom-data-store#ituscreationstore) and [ITusReadableStore](https://github.com/tusdotnet/tusdotnet/wiki/Custom-data-store#itusreadablestore). This will allow the store to create and upload files and to read the files back for processing or downloading.

There are multiple ways to integrate with a tus server. The most common one is to allow the client to create the upload resource but there are cases where you wish to create the upload resource using some other api and just give the client the URL to the resource. In your error message, the client tries to create the resource (using a POST to the /files endpoint) and since the store does not allow this, tusdotnet returns `404 Not Found`. You can either implement the creation interface, or give the client a unique resource url to upload the data to.

**Comment by tzupetic** [comment]
Hi,
thanks for the answer. I figured out that I was missing ITusCreationStore. 
Best regards.
