### ISSUE TITLE
Handle file name with symbol like #

### ISSUE THREAD

**Issue by benny-adiwijaya** [tusdotnet/tusdotnet#214]
Hi, I need to upload files with the original filename but it did not work when there is symbol like # in the name. Is there way to handle filename with symbol like # gracefully? The issue is likely related to how the URL is being processed. In URLs, the # symbol and anything following it is considered the fragment identifier. When the browser makes an HTTP request to the server, it only sends the part of the URL before the # and it can not find the file.

**Comment by smatsson** [comment]
If you are transferring the unencoded filename in URL you will have issues with # since that's a part of the URL that, as you said, will not be sent to the server. You will need to either encode the filename part of the URL or transfer it through metadata (which is the default behavior in tusdotnet).
