### ISSUE TITLE
400 error?

### ISSUE THREAD

**Issue by drphilgarner** [tusdotnet/tusdotnet#43]
Hi - done some work adapting this project for Azure blob storage (still in dev). Works great with included JS client but I am now trying with the [Android Client](https://github.com/tus/tus-android-client) and get a 400 error. I have the android client working with the official test instance at https://master.tus.io/files - so that's known working too. Any idea what's going wrong? Using the Owin netcore app btw.

Thanks for your work on this project!

**Comment by drphilgarner** [comment]
OK done a bit more investigating, looks like it fails on metadata checks:

`
                            if (!ctx.Metadata.ContainsKey("name"))
                            {
                                ctx.FailRequest("name metadata must be specified. ");
                            }

                            if (!ctx.Metadata.ContainsKey("contentType"))
                            {
                                ctx.FailRequest("contentType metadata must be specified. ");
                            }
`
The android client sends a key as _filename_ not _name_, and also does not send a `contentType` key at all. If I make these changes all works as expected. I'm not a tus expert - don't know if those things are part of the standard?

**Comment by smatsson** [comment]
Hi @drphilgarner 

The protocol does not specify any metadata what so ever. This is entirely up to the server and client to decide on. 

The code you have provided above is for the `OnBeforeCreateAsync` event. This event can be used by the server to validate a file before creating it so that all required metadata is present. The code in the test site just sets up some metadata as an example. There is no requirement to have these properties or any properties for that matter.

You could just remove the `OnBeforeCreateAsync` event handler, change the code to validate `filename` instead or add `name` as a property in the Android client. All of these are valid according to the protocol.

**Comment by drphilgarner** [comment]
Ok great, thanks for the clarification.

**Comment by smatsson** [comment]
No worries, feel free to open new issues if you have any more questions :)

**Comment by smatsson** [comment]
Btw if you decide to make your blob storage store public please let me know and I'll add a link to your github.

**Comment by drphilgarner** [comment]
Well it's in a workable state now @smatsson https://github.com/drphilgarner/tusdotnet very basic implementation using Azure blob stores, tested on the Owin site.

**Comment by smatsson** [comment]
Cool! Thanks for sharing. I started working on a store using append blobs but found append blobs to be really, really slow. Haven't done any work on it since August (and it's not made public). What's your experience with the performance of append blobs? 

If you decide to extract the actual store into its own project/nuget, please let me know and I'll gladly add a link to the readme or wiki.

**Comment by drphilgarner** [comment]
Not really tested it well enough yet. You could be right on the speed. I
was wondering about abstracting all the small files tus uses to maintain
state to a database and just using the blob to store the actual files. What
do you think?

**Comment by smatsson** [comment]
In the version I made I used the blob's metadata to store all the small files. It worked fairly well as that part felt much faster than actually writing data to the blob. I would probably not want to use different tech to store actual files and the rest of the data (e.g using SQL for metadata and blob storage for files).

**Comment by smatsson** [comment]
Found the code on my computer and uploaded it here: https://github.com/smatsson/TusAzureStore

Feel free to use any bits and pieces that you find useful.

**Comment by drphilgarner** [comment]
Great, thanks Stefan, will take a look.
