### ISSUE TITLE
Accessing DB context from 

### ISSUE THREAD

**Issue by j-hudecek** [tusdotnet/tusdotnet#45]
How can I access my DB context from event handlers? For example I would like to check access rights in a different method, hand out tokens for my clients and then in OnBeforeCreateAsync connect to database and check that the valid token has been supplied or update database that file has been uploaded in OnFileCompleteAsync.

**Comment by smatsson** [comment]
It depends on what framework you are on. If running on asp.net core I would suggest using AsyncLocal to get a per request static instance of your DbContext that you can use. https://msdn.microsoft.com/en-us/library/dn906268(v=vs.110).aspx

On OWIN you could use the same technique as above or use HttpContext.Current (if you are referencing System.Web).

Ideally one would like to have the IServiceCollection from asp.net core in the event context but since tusdotnet runs on multiple frameworks this isn't possible in an easy way.

**Comment by j-hudecek** [comment]
I'm on .Net Core 2.0.
If I inject it into Configure by the time the OnBeforeCreateAsync executes it's disposed.  I think that using AsyncLocal would have the same problem - the issue isn't getting a reference to dbcontext.
I think it would have to get injected in Invoke: https://github.com/tusdotnet/tusdotnet/blob/8872d101d3aa440ca83b98fcc6d00a11e541c059/Source/tusdotnet/ExternalMiddleware/Core/TusCoreMiddleware.cs#L34

**Comment by SasaCetkovic** [comment]
I have solved it like this:

public void ConfigureServices(IServiceCollection services)
{
    services.AddScoped<MyCustomTusConfiguration>();
}

public void Configure(IApplicationBuilder app, IServiceProvider serviceProvider, ILoggerFactory loggerFactory)
        {
...
            app.UseTus(context => context.RequestServices.GetService<MyCustomTusConfiguration>());
            app.UseMvc();
        }


So far so good.

**Comment by j-hudecek** [comment]
Thanks for the pointers, really appreciate it.
