### ISSUE TITLE
Name casing

### ISSUE THREAD

**Issue by Jon-Indico** [tusdotnet/tusdotnet#55]
This is a minor thing, but it's bugging me, so here goes. Would it be possible for the next major release to rename the namespace and package name to conform to .NET naming standards?

I know this is non-issue, but you know... PascalCaseAllTheThings!

**Comment by smatsson** [comment]
Thanks for the feedback! The official docs has this to say on the subject:

"If your brand employs nontraditional casing, you should follow the casing defined by your brand, even if it deviates from normal namespace casing."

https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces

So that will be a "no" 😊

**Comment by Jon-Indico** [comment]
You probably have whole directory full of .NET projects with all lowercase names, haven't you... You. You... monster! 😱

But seriously though, thanks for responding.

**Comment by smatsson** [comment]
Moahaha you know it 👹
