### ISSUE TITLE
Making the store path depending on identity 

### ISSUE THREAD

**Issue by IAmNotGoodWithComputers** [tusdotnet/tusdotnet#56]
Hi

I checked your library and I love it! I was going to try to implement my own but I'm so glad that someone already did this. You're amazing!

But, due to the current design of the library, I can't think of any way to make the upload path depend on the Identity of the requester, without having to implement my own store and injecting the SignInManager. 

I'm sure I'm not the first one to try this. Can you maybe hint me a nice way to do that?

What I basically want to do is, to upload files to `/opt/uploads/{user.Id}/`

I'm using dotnet core btw.

(Also I'm very sorry that I'm using your issue board as tech support :D)

**Comment by drphilgarner** [comment]
I'd rethink your design approach. For my app I have a database that tracks the tusfile uploads with a guid associated with a user. I use a guid for the filename for the file from Tus and track it with any other metadata I need. Works fine.

**Comment by IAmNotGoodWithComputers** [comment]
Thanks, it appears that I had a wrong understanding on the protocol in the first place and how metadata is to be used. It looks like a good solution!

**Comment by smatsson** [comment]
I feel that this was not entirely answered or that the question might be misunderstood. As I understand it @IAmNotGoodWithComputers you wish to have different upload paths for different users of your system? This has been supported since the early versions of tusdotnet.

When you setup tusdotnet (`app.UseTus`) you provide a configuration factory that is called on _every_ request. The returned config from the factory is then used as configuration for that request. You can return different configurations based on the provided httpContext as such:

 ```
app.UseTus(httpContext =>
{
    if (!httpContext.User.Identity.IsAuthenticated)
    {
        // Will disable tusdotnet for this request in 2.2 (not yet released)
        // Will throw NullReferenceExceptions in < 2.2
        return Task.FromResult<DefaultTusConfiguration>(null);
    }

    var userName = httpContext.User.Identity.Name;

    // Note: Make sure that username does not contain special characters suchs as "../" or similar.
    var urlPath = "/files/" + userName;
    var diskPath = @"C:\tusfiles\" + userName;

    if (!System.IO.Directory.Exists(diskPath))
        System.IO.Directory.CreateDirectory(diskPath);

    return Task.FromResult(new DefaultTusConfiguration
    {
        UrlPath = urlPath,
        Store = new TusDiskStore(diskPath)
    });
});
```

Given the above configuration, user `stefan` would upload files to `/files/stefan` and files would be saved in `C:\tusfiles\stefan`.

**Comment by Breinich** [comment]
Hello @smatsson!

Is there a way to do the same (dynamic url and disk paths based on the request) via the endpoint routing setup or shall I switch to the UseTus option?

By the way lots of thanks for this implementation, I so much like the quality of the source code and also the wiki/documentation and the support for it!

**Comment by smatsson** [comment]
@Breinich The same type of configuration factory is used for both MapTus and UseTus so you can use the same technique as above. 

> By the way lots of thanks for this implementation, I so much like the quality of the source code and also the wiki/documentation and the support for it!

Thanks for the kind words!

**Comment by Breinich** [comment]
@smatsson  As I understand MapTus will only listen on the specified path (i.e. /files/) and what I thought about is that could I map dynamic url paths via MapTus (i.e. based on the user names, but that's not the point)? 

Because if I use MapTus, as I understand, I shouldn't set the urlPath in the configuration factory, because the MapTus will only listen on /files/ and if I change the upload url, the server won't be able to handle the uploaded data on that path. I've tried to introduce some path variables like /files/{folder}/, but I didn't succeed, I wasn't that surprised, but at least I gave it a chance.

So maybe I just need some better understanding, how the endpoint routing works. It's not a problem for me to leave the upload url as it is and store the files in different folders, I was just wondering whether could I make it a bit cleaner and more beautiful.

**Comment by smatsson** [comment]
@Breinich Not really sure what issue you ran in to but this example works as expected. 

```
app.MapTus("/{whatever}/", httpContext =>
{
    var folder = httpContext.GetRouteValue("whatever") as string;

    return Task.FromResult<DefaultTusConfiguration>(new()
    {
        Store = new TusDiskStore(@"c:\tusfiles\" + folder)
    });
});
```

**Comment by Breinich** [comment]
Thanks, I'll try this later. 
What I did wrong is maybe that I wanted to set the urlPath property to that url too.
