### ISSUE TITLE
Problem uploading files with specific extensions

### ISSUE THREAD

**Issue by michaelrall** [tusdotnet/tusdotnet#79]
Hello,

I'm currently testing tus on dot-net-core 3.0 plattform and I'm facing a weird problem.

I can't upload SOME of my local test-files. The problem is repeatable and even copying and renaming the problematic file doesn't help. Uploading to the official test-backend is working, so I assume it's a problem with tusdotnet.

I'm using tusdotnet 2.2.2, using testsite-project Core 3.0. I'm using the official tus js-client 1.8.0, browser based demo.

I modified the testsite-project in the following way:
- Added CORS as suggested in the docs -> working
- removed meta-data-checking in 'OnBeforeCreateAsync' -> working

Uploading .png, .zip (several megabytes) is working fine, but uploading a .docx or .k9s file fails with a 400-Error saying:
"Header Upload-Metadata: The Upload-Metadata request and response header MUST consist of one or more comma - separated key - value pairs. The key and value MUST be separated by a space.The key MUST NOT contain spaces and commas and MUST NOT be empty. The key SHOULD be ASCII encoded and the value MUST be Base64 encoded.All keys MUST be unique."

Copying and renaming the file has no effect. When I change the extension it's working...

Any ideas where to chase for that?

cheers Michael

**Comment by michaelrall** [comment]
I found the problematic line, it's Metadata.cs:113 - there is a key "filetype" in the METADATA, but it has no value, so the pairParts.Length is 1 not 2 -> Ex

**Comment by michaelrall** [comment]
I further digged into to js-client and found indeed that with my problematic files the "filetype" is not set (I think it tries some known MIME-Types). So basically I would say, that filetype is not a MUST field, but it can be empty. The official server accepts these, so I guess this would be the desired behaviour.

I see the intention of your check if there are pairs in the meta-data, but in this case its a bit too eager I think.

I read some Issues from 2016-2018 where they discussed similar problems in the js-client, and according to the documentiation your implementation is the correct one - maybe you could check back to the tus-guys what they are thinking, to change the js-client to not pass empty fields or to soften your checks.

**Comment by smatsson** [comment]
Hi,

First of all, thank you for writing a very descriptive, thought through issue. It makes my life a lot easier if I can understand what you are actually asking.

Seems like we are missing the last part of [the spec](https://tus.io/protocols/resumable-upload.html#upload-metadata) in the implementation (my highlight):

"The Upload-Metadata request and response header MUST consist of one or more comma-separated key-value pairs. The key and value MUST be separated by a space. The key MUST NOT contain spaces and commas and MUST NOT be empty. The key SHOULD be ASCII encoded and the value MUST be Base64 encoded. All keys MUST be unique. **The value MAY be empty. In these cases, the space, which would normally separate the key and the value, MAY be left out.**".

I.e this is a valid header:
```
upload-metadata: name dGVzdGZpbGUxMG1iLmJpbg==,contentType
```

It also seems that tusd allows metadata that is not encoded correctly, e.g.
```
upload-metadata: name notbase64,contentType
```

I would argue that the first is a bug in tusdotnet and the latter a bug in tusd.




> I further digged into to js-client and found indeed that with my problematic files the "filetype" is not set (I think it tries some known MIME-Types). So basically I would say, that filetype is not a MUST field, but it can be empty. The official server accepts these, so I guess this would be the desired behaviour.

I think the problem with the js-client is that it must depend on the browser for giving you the file type. I've had issues with this in several projects where different browsers/OSes report different types for the same file so I wouldn't trust it for anything important. 


Anyhow, I'll tag this issue as bug an get it sorted so that tusdotnet allows empty values in keys. 

Once again, thanks for reporting. I hope you like the lib.

**Comment by michaelrall** [comment]
Hi,

thanks for your quick response. For me it's not ultra urgent, so I'll just wait for the next patch of tusdotnet.

I see that the filetype determination is a very browser-specific issue, so either way I will not rely on this and determine the file content-type on the serverside with custom logic.

And yes, I like TUS and your lib, I stumbled across it some days ago, but its exactly what I need for my new product. It took me just some hours to integrate tusdotnet into an existing service-stack application :-)

**Comment by smatsson** [comment]
Glad to hear it! You should be able to bypass this for now by using a default value for the type metadata. Something like this (copied from index.html in the ASP.NET Core 3.1 test site):

```javascript
upload = new tus.Upload(file,
{
    endpoint: 'files/',
    onError: onTusError,
    onProgress: onTusProgress,
    onSuccess: onTusSuccess,
    metadata: {
        name: file.name,
        contentType: file.type || 'application/octet-stream' // <-- this line 
    }
});
```

**Comment by michaelrall** [comment]
Thanks for the hint - I already handle it that way :-)

**Comment by smatsson** [comment]
Just an update. It seems that the protocol was changed after the intial release to include this behavior. The initial 1.0 protocol that tusdotnet was built for does not allow this.

Source: https://github.com/tus/tus-resumable-upload-protocol/pull/90

No worries though, we will implement this.

**Comment by smatsson** [comment]
I find it a bit weird to update the protocol without updating the version so I created an issue over at https://github.com/tus/tus-resumable-upload-protocol/issues/149 to get some clarification.

**Comment by smatsson** [comment]
2.3 is now out: https://www.nuget.org/packages/tusdotnet/2.3.0
