### ISSUE TITLE
OnFileCompleteAsync METHOD ERROR

### ISSUE THREAD

**Issue by anu035** [tusdotnet/tusdotnet#81]
I am new in dot net i did all the things mentioned in repositopry but
i found  DoSomeProcessing and  MyProcessingException giving error.please help me what should writtent there to return file in case of success and error i case of error.

**Comment by smatsson** [comment]
Hi!

Welcome to the wonderful world of .NET =) 

Are you talking about the `DoSomeProcessing` method call in the readme example? That is just an example on how to use tusdotnet's `OnFileCompleteAsync` callback. You will need to implement your own processing since tusdotnet cannot know what you want to do with the file.

I'm not sure what `MyProcessingException` is or where you found it?

**Comment by smatsson** [comment]
Closing due to no answer for a week.
