### ISSUE TITLE
Change Store path foreach Upload

### ISSUE THREAD

**Issue by Epy92** [tusdotnet/tusdotnet#94]
Hi,

I tried changing the path of the Store for each upload but did not work by changing the Store property in OnAuthorize or OnBeforeCreate events. Is there any other way to achieve that other than doing the custom storage implementation?

Many thanks

**Comment by smatsson** [comment]
Hi,

The configuration factory is designed for exactly this use case:

```
app.UseTus(async httpContext => 
{
    string storagePath = await GetStoragePathSomehow(httpContext);

    return new DefaultTusConfiguration
    {
        Store = new TusDiskStore(storagePath)
        ...
    }
});
```

The method provided to `app.UseTus` will run on every request and can return different configurations for each request. Return null to disable tusdotnet for the request.

**Comment by Epy92** [comment]
I did so but what I am trying to achieve is to have a different directory each time an upload is done. This is the method that creates new path:

```
        public string GetNewPathForUpload() {
            var path = Path.Combine(@"\\UNCPath\TusFiles", _securityContext.TenantId.ToString(), Guid.NewGuid().ToString());
            if (!Directory.Exists(path)) {
                Directory.CreateDirectory(path);
            }
            return path;
        }
```

This method is called many times (also on page load) and it creates around 4-5 directories and in the final upload fails with the following errors:
![image](https://user-images.githubusercontent.com/19517946/87144683-d3b35780-c2b0-11ea-812e-5540204e55a2.png)

Removing the new Guid from construction of the path works.

**Comment by smatsson** [comment]
I don't follow what you are trying to achieve? A tus upload consists of multiple HTTP requests for a single file and each request must use the same path, otherwise the file won't be found and a `404 Not Found` will be returned. 

Basic flow:

1. POST /files -> Creates the file in the path specified in the configuration.
2. PATH /files/fileid -> Uploads data to the file created in step one. Path must match where the file was created, otherwise the file cannot be found and thus cannot be written.

**Comment by Epy92** [comment]
You're right. I was missing that. I was trying to have every uploaded file in it's own directory. I'll found an workaround
